datasources:
  HTTP:
    http-1:
      port: 8000
      device: "lo0"
  HTTP2:
    http2-1:
      port: 5050
      device: "lo0"
  GRPC:
    grpc-1:
      port: 50051
      device: "lo0"
#  MYSQL:
#    mysql-1:
#      port: 3306
#      device: "lo0"
