datasources:
  HTTP:
    inventory-http-1:
      port: 4567
      device: "lo0"
    inventory-ddb-1:
      port: 8888
      device: "lo0"
#  HTTP2:
#    grpc-1:
#      port: 50051
#      device: "lo0"
#  MYSQL:
#    mysql-1:
#      port: 3306
#      device: "lo0"
